source "https://rubygems.org", cooldown: 7

ruby file: ".tool-versions"
gem "rails", "8.1.3"
gem "pinned_exact", "1.2.3"
gem 'single_quoted', '2.0.0'
gem "with_options", "1.24.5", require: false
gem "commented_pin", "3.1.0" # locked: breaking changes in 4.x
gem "kamal", require: false
gem "range_pin", ">= 1.0", "< 2.0"

group :development, :test do
  gem "grouped_gem", "0.9.1"
end
